"""Meta-Strategy Composer — risk-adjusted portfolio optimization.

Ported from resource/nuvia-agentkit/ai-engine/modules/meta_strategy/optimizer.py.
Uses scipy SLSQP. Each protocol entry optionally carries a `chain_id` so the
resulting allocation can name both protocol and chain (multi-chain).
"""
from __future__ import annotations

from typing import Callable, Dict, List, Optional

import numpy as np
from loguru import logger
from scipy.optimize import minimize

# Optional LLM hook: injected by callers (ai_engine) so reasoning text can be
# generated by the model with a heuristic fallback.
ReasoningFn = Callable[[Dict, List[str], List[float], str], str]


class StrategyOptimizer:
    """Optimizes yield allocation across protocols/chains to maximize risk-adjusted return."""

    def __init__(self) -> None:
        self.min_allocation = 0.05  # min 5% per protocol
        self.max_allocation = 0.50  # max 50% per protocol

    def optimize_allocation(
        self,
        protocols: List[str],
        expected_apys: List[float],
        risk_scores: List[float],
        risk_tolerance: str = "moderate",
        *,
        chain_ids: Optional[List[int]] = None,
        reasoning_fn: Optional[ReasoningFn] = None,
    ) -> Dict:
        try:
            n = len(protocols)
            if n == 0:
                return self._default_strategy(risk_tolerance)

            expected_returns = np.array(expected_apys, dtype=float) / 100
            risks = np.array(risk_scores, dtype=float) / 10

            params = {
                "conservative": {"risk_weight": 2.0},
                "moderate": {"risk_weight": 1.0},
                "aggressive": {"risk_weight": 0.5},
            }.get(risk_tolerance, {"risk_weight": 1.0})
            risk_penalty = params["risk_weight"]

            def objective(weights):
                portfolio_return = np.dot(weights, expected_returns)
                portfolio_risk = np.dot(weights, risks)
                return -(portfolio_return - risk_penalty * portfolio_risk)

            constraints = [{"type": "eq", "fun": lambda w: np.sum(w) - 1.0}]
            bounds = [(self.min_allocation, self.max_allocation) for _ in range(n)]
            x0 = np.ones(n) / n

            result = minimize(objective, x0, method="SLSQP", bounds=bounds,
                              constraints=constraints, options={"maxiter": 1000})

            if not result.success:
                logger.warning(f"Optimization did not converge: {result.message}")
                allocations = self._fallback_weights(protocols, expected_apys, risks)
            else:
                allocations = {p: round(float(w) * 100, 1) for p, w in zip(protocols, result.x)}

            # Re-normalize to 100 after rounding.
            total = sum(allocations.values()) or 1
            allocations = {p: round(v / total * 100, 1) for p, v in allocations.items()}

            portfolio_apy = sum(allocations[p] / 100 * expected_apys[i] for i, p in enumerate(protocols))
            portfolio_risk = sum(allocations[p] / 100 * risk_scores[i] for i, p in enumerate(protocols))

            reasoning = (reasoning_fn(allocations, protocols, risk_scores, risk_tolerance)
                         if reasoning_fn else
                         self._explain_allocation(allocations, expected_apys, risk_scores, protocols, risk_tolerance))

            chain_allocation = []
            if chain_ids:
                for i, protocol in enumerate(protocols):
                    chain_allocation.append({
                        "protocol": protocol,
                        "chain_id": chain_ids[i],
                        "allocation": allocations.get(protocol, 0),
                        "expected_apy": round(float(expected_apys[i]), 2),
                        "risk_score": round(float(risk_scores[i]), 1),
                    })

            return {
                "strategy_id": f"mom3-{risk_tolerance}-{int(abs(hash(tuple(protocols)))) % 10_000}",
                "allocations": allocations,
                "chain_allocations": chain_allocation,
                "expected_apy": round(float(portfolio_apy), 2),
                "risk_score": round(float(portfolio_risk), 2),
                "risk_tolerance": risk_tolerance,
                "reasoning": reasoning,
                "diversification_score": self._calculate_diversification(allocations),
            }
        except Exception as exc:
            logger.error(f"Optimization error: {exc}")
            return self._fallback_allocation(protocols, expected_apys, risks, risk_tolerance)

    def _fallback_weights(self, protocols: List[str], apys: List[float], risks: np.ndarray) -> Dict[str, float]:
        scores = np.array(apys, dtype=float) / (1 + np.array(risks, dtype=float))
        weights = scores / scores.sum()
        weights = np.clip(weights, self.min_allocation, self.max_allocation)
        weights = weights / weights.sum()
        return {p: round(float(w) * 100, 1) for p, w in zip(protocols, weights)}

    def _fallback_allocation(self, protocols, apys, risks, risk_tolerance) -> Dict:
        allocations = self._fallback_weights(protocols, apys, risks)
        portfolio_apy = sum(allocations[p] / 100 * apys[i] for i, p in enumerate(protocols))
        return {
            "strategy_id": "mom3-fallback",
            "allocations": allocations,
            "chain_allocations": [],
            "expected_apy": round(float(portfolio_apy), 2),
            "risk_score": 5.0,
            "risk_tolerance": risk_tolerance,
            "reasoning": "Balanced allocation based on risk-adjusted returns (fallback).",
            "diversification_score": 0.75,
        }

    @staticmethod
    def _explain_allocation(allocations, apys, risks, protocols, risk_tolerance) -> str:
        top_protocol = max(allocations.items(), key=lambda x: x[1])
        top_idx = protocols.index(top_protocol[0])
        parts = [
            f"Allocated {top_protocol[1]}% to {top_protocol[0]} for the best risk-adjusted return "
            f"({apys[top_idx]}% APY, risk {risks[top_idx]:.1f}/10).",
            f"Diversified across {sum(1 for v in allocations.values() if v >= 10)} protocols to limit risk.",
        ]
        if risk_tolerance == "conservative":
            parts.append("Conservative stance: stability prioritized over maximum yield.")
        elif risk_tolerance == "aggressive":
            parts.append("Aggressive stance: maximizing yield with higher risk tolerance.")
        return " ".join(parts)

    @staticmethod
    def _calculate_diversification(allocations: Dict[str, float]) -> float:
        weights = np.array(list(allocations.values()), dtype=float) / 100
        n = len(weights)
        if n == 0:
            return 0.0
        herfindahl = float(np.sum(weights ** 2))
        max_herf, min_herf = 1.0, 1.0 / n if n else 1.0
        denom = (max_herf - min_herf) or 1.0
        return round((max_herf - herfindahl) / denom, 2)

    @staticmethod
    def _default_strategy(risk_tolerance) -> Dict:
        return {
            "strategy_id": "default",
            "allocations": {},
            "chain_allocations": [],
            "expected_apy": 0,
            "risk_score": 0,
            "risk_tolerance": risk_tolerance,
            "reasoning": "No protocols available for this chain.",
            "diversification_score": 0,
        }

    def compare_strategies(
        self,
        current_allocation: Dict[str, float],
        proposed_allocation: Dict[str, float],
        protocol_apys: Dict[str, float],
    ) -> Dict:
        def calc(alloc):
            return sum((alloc.get(p, 0) / 100) * protocol_apys.get(p, 0) for p in protocol_apys)

        current_apy = calc(current_allocation)
        proposed_apy = calc(proposed_allocation)
        apy_improvement = proposed_apy - current_apy

        changes = []
        for protocol in set(list(current_allocation) + list(proposed_allocation)):
            diff = proposed_allocation.get(protocol, 0) - current_allocation.get(protocol, 0)
            if abs(diff) >= 5:
                changes.append({"protocol": protocol, "change": round(diff, 1),
                                "direction": "increase" if diff > 0 else "decrease"})
        return {
            "current_apy": round(current_apy, 2),
            "proposed_apy": round(proposed_apy, 2),
            "apy_improvement": round(apy_improvement, 2),
            "changes": changes,
            "recommendation": "execute" if apy_improvement > 0.5 else "hold",
        }


# Singleton ---------------------------------------------------------------------
_optimizer: StrategyOptimizer | None = None


def get_strategy_optimizer() -> StrategyOptimizer:
    global _optimizer
    if _optimizer is None:
        _optimizer = StrategyOptimizer()
    return _optimizer
